"""
Django settings for ecourseapis project.

Generated by 'django-admin startproject' using Django 5.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-puefaojq+qauej!=cu%q1w1n%3o42*dvzv1c!*a-ez@@7f%pby'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["192.168.0.100", "192.168.0.105", "192.168.1.13","127.0.0.1","Hoangila2016.pythonanywhere.com"]

# Application definition

INSTALLED_APPS = [
    # 'theses',
    'theses.apps.CoursesConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'ckeditor',
    'corsheaders',
    'ckeditor_uploader',
    'rest_framework',
    'drf_yasg',
    'oauth2_provider',
]

AUTH_USER_MODEL = 'theses.NguoiDung'

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'gtapis.urls'
CORS_ALLOW_ALL_ORIGINS = True
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'gtapis.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'Hoangila2016$gt_db',
        'USER': 'Hoangila2016',
        'PASSWORD': 'Admin@123',
        'HOST': 'Hoangila2016.mysql.pythonanywhere-services.com'  # mặc định localhost
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True
TIME_ZONE = 'Asia/Ho_Chi_Minh'  # Chọn múi giờ bạn muốn sử dụng
USE_TZ = True  # Bật tính năng múi giờ của Django
WSGI_APPLICATION = 'gtapis.wsgi.application'
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = '/home/Hoangila2016/Graduate-Thesis-Management-System/gt_apis/theses/static'
# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = '/media/'
# MEDIA_ROOT = '/home/Hoangila2016/Graduate-Thesis-Management-System/gt_apis/theses/static' # để Khánh thêm user xíu rồi sửa sau, nó báo lỗi media_root với static_root phải khác nhau
MEDIA_ROOT = '%s/theses/static/' % BASE_DIR
import pymysql

pymysql.install_as_MySQLdb()

CKEDITOR_UPLOAD_PATH = "ckeditor/images/"

import cloudinary
import cloudinary.uploader
import cloudinary.api

cloudinary.config(
    cloud_name="dfab9smwx",
    api_key="995859748728177",
    api_secret="Ii0pGYRuN4rzTscRYWLeSgg1cCQ",
)

REST_FRAMEWORK = {
    # "DEFAULT_PAGINATION_CLASS":
    #     "rest_framework.pagination.PageNumberPagination",
    # "PAGE_SIZE": 2,
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'oauth2_provider.contrib.rest_framework.OAuth2Authentication',
    )
}

CLIENT_ID = "NmvFSir1yfbpoN50RPkVrj4ihDQfHfANLxm2AK7i"
CLIENT_SECRET = "QKKu0sRz0Nf05Jb6T0mxnZbJ5IcyeOq5X7PHYhDlr9yYM4oyrdnjrJw5fvzi1MAVP73TgMWQi8Ry5yaj3LudlrPxW1IUpWRRzSqf2ZYJ5yP9qki0KXuZFFkLMRQQVrwx"


# SEND MAIL SETTINGS
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'howtocarrythisteam@gmail.com'
EMAIL_HOST_PASSWORD = 'krlk pboc pxpr haze' # 'Bichnibich'