# Generated by Django 5.0.3 on 2024-04-21 09:15

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='NguoiDung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('avatar', models.ImageField(default='static/graduatethesis/Quy trình tập luyện sau khi thuộc động tác nhưng chưa có tempo.png.jpg', upload_to='graduatethesis/%Y/%m')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='KhoaLuanTotNghiep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('trang_thai', models.BooleanField(default=True)),
                ('ten_khoa_luan', models.CharField(max_length=200)),
                ('ty_le_dao_van', models.FloatField()),
                ('diem_tong', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='NganhHoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('trang_thai', models.BooleanField(default=True)),
                ('ten_nganh', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GiangVien',
            fields=[
                ('nguoidung_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('bang_cap', models.CharField(max_length=100)),
                ('kinh_nghiem', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Giảng Viên',
                'verbose_name_plural': 'Giảng Viên',
            },
            bases=('theses.nguoidung',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='GiaoVu',
            fields=[
                ('nguoidung_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('trinh_do', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Giáo Vụ',
            },
            bases=('theses.nguoidung',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Lop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('trang_thai', models.BooleanField(default=True)),
                ('ten_lop', models.CharField(max_length=100)),
                ('si_so', models.IntegerField()),
                ('nganh', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='theses.nganhhoc')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TieuChi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('tieu_chi', models.CharField(max_length=200)),
                ('ty_le', models.FloatField()),
                ('kltn', models.ManyToManyField(blank=True, related_name='tieu_chi', to='theses.khoaluantotnghiep')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KLTNGVHuongDan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('kltn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theses.khoaluantotnghiep')),
                ('gv_huong_dan', models.ManyToManyField(blank=True, to='theses.giangvien')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HoiDongBVKL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('trang_thai', models.BooleanField(default=True)),
                ('ngay_bao_ve', models.DateField()),
                ('chu_tich', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chu_tich', to='theses.giangvien')),
                ('gv_phan_bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gv_phan_bien', to='theses.giangvien')),
                ('thanh_vien', models.ManyToManyField(blank=True, to='theses.giangvien')),
                ('thu_ky', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thu_ky', to='theses.giangvien')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SinhVien',
            fields=[
                ('nguoidung_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL)),
                ('mssv', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('nam_nhap_hoc', models.IntegerField()),
                ('lop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='theses.lop')),
            ],
            options={
                'verbose_name': 'Sinh Viên',
                'verbose_name_plural': 'Sinh Viên',
            },
            bases=('theses.nguoidung',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='khoaluantotnghiep',
            name='mssv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theses.sinhvien'),
        ),
        migrations.CreateModel(
            name='Diem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('diem', models.FloatField()),
                ('kltn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theses.khoaluantotnghiep')),
                ('tieu_chi', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='theses.tieuchi')),
                ('gv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theses.giangvien')),
            ],
            options={
                'unique_together': {('tieu_chi', 'gv', 'kltn')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='khoaluantotnghiep',
            unique_together={('id', 'mssv')},
        ),
    ]
