# Generated by Django 5.0.3 on 2024-04-25 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khoaluantotnghiep',
            name='diem_tong',
            field=models.FloatField(null=True),
        ),
    ]
